In [1]:
from datasets import load_dataset
ds = load_dataset("elenanereiss/german-ler")

/home/tfischer/micromamba/envs/dwts/lib/python3.11/site-packages/datasets/load.py:1486: FutureWarning: The repository for elenanereiss/german-ler contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/elenanereiss/german-ler
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(

In [3]:
df = ds["test"].to_pandas()

In [4]:
df.head()

,id,tokens,ner_tags,ner_coarse_tags
0,0,"[Wegen, der, Teilnahme, des, Antragstellers, a...","[38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 3...","[14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 1..."
1,1,"[●, Mitwirkung, im, Sinne, der, Kostenverfügung]","[38, 38, 38, 38, 38, 38]","[14, 14, 14, 14, 14, 14]"
2,2,"[Von, der, Ablehnung, eines, Straferlasses, fü...","[38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 3...","[14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 1..."
3,3,"[Zwar, führt, bei, der, in, §, 33, Abs., 2, TV...","[38, 38, 38, 38, 38, 18, 37, 37, 37, 37, 37, 3...","[14, 14, 14, 14, 14, 5, 12, 12, 12, 12, 12, 12..."
4,4,"[Der, Wortlaut, der, Zulagenregelung, verlange...","[38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 3...","[14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 1..."

In [5]:
df["fine_ner_tags"] = df["ner_tags"]
df["ner_tags"] = df["ner_coarse_tags"]
del df["ner_coarse_tags"]

In [10]:
df.head()

,id,tokens,ner_tags,fine_ner_tags
0,0,"[Wegen, der, Teilnahme, des, Antragstellers, a...","[14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 1...","[38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 3..."
1,1,"[●, Mitwirkung, im, Sinne, der, Kostenverfügung]","[14, 14, 14, 14, 14, 14]","[38, 38, 38, 38, 38, 38]"
2,2,"[Von, der, Ablehnung, eines, Straferlasses, fü...","[14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 1...","[38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 3..."
3,3,"[Zwar, führt, bei, der, in, §, 33, Abs., 2, TV...","[14, 14, 14, 14, 14, 5, 12, 12, 12, 12, 12, 12...","[38, 38, 38, 38, 38, 18, 37, 37, 37, 37, 37, 3..."
4,4,"[Der, Wortlaut, der, Zulagenregelung, verlange...","[14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 1...","[38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 3..."

In [12]:
fine_labels=[
    'B-AN', 
    'B-EUN', 
    'B-GRT', 
    'B-GS', 
    'B-INN', 
    'B-LD', 
    'B-LDS', 
    'B-LIT', 
    'B-MRK', 
    'B-ORG', 
    'B-PER', 
    'B-RR', 
    'B-RS', 
    'B-ST', 
    'B-STR', 
    'B-UN', 
    'B-VO', 
    'B-VS', 
    'B-VT', 
    'I-AN', 
    'I-EUN', 
    'I-GRT', 
    'I-GS', 
    'I-INN', 
    'I-LD', 
    'I-LDS', 
    'I-LIT', 
    'I-MRK', 
    'I-ORG', 
    'I-PER', 
    'I-RR', 
    'I-RS', 
    'I-ST', 
    'I-STR', 
    'I-UN', 
    'I-VO', 
    'I-VS', 
    'I-VT', 
    'O'
]

In [13]:
id2fine_label = {i: label for i, label in enumerate(fine_labels)}

In [14]:
id2fine_label

{0: 'B-AN',
 1: 'B-EUN',
 2: 'B-GRT',
 3: 'B-GS',
 4: 'B-INN',
 5: 'B-LD',
 6: 'B-LDS',
 7: 'B-LIT',
 8: 'B-MRK',
 9: 'B-ORG',
 10: 'B-PER',
 11: 'B-RR',
 12: 'B-RS',
 13: 'B-ST',
 14: 'B-STR',
 15: 'B-UN',
 16: 'B-VO',
 17: 'B-VS',
 18: 'B-VT',
 19: 'I-AN',
 20: 'I-EUN',
 21: 'I-GRT',
 22: 'I-GS',
 23: 'I-INN',
 24: 'I-LD',
 25: 'I-LDS',
 26: 'I-LIT',
 27: 'I-MRK',
 28: 'I-ORG',
 29: 'I-PER',
 30: 'I-RR',
 31: 'I-RS',
 32: 'I-ST',
 33: 'I-STR',
 34: 'I-UN',
 35: 'I-VO',
 36: 'I-VS',
 37: 'I-VT',
 38: 'O'}

In [15]:
df["fine_ner_tags"] = df["fine_ner_tags"].apply(lambda x: [id2fine_label[i] for i in x])

In [16]:
df.head()

,id,tokens,ner_tags,fine_ner_tags
0,0,"[Wegen, der, Teilnahme, des, Antragstellers, a...","[14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 1...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, B-L..."
1,1,"[●, Mitwirkung, im, Sinne, der, Kostenverfügung]","[14, 14, 14, 14, 14, 14]","[O, O, O, O, O, O]"
2,2,"[Von, der, Ablehnung, eines, Straferlasses, fü...","[14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 1...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3,3,"[Zwar, führt, bei, der, in, §, 33, Abs., 2, TV...","[14, 14, 14, 14, 14, 5, 12, 12, 12, 12, 12, 12...","[O, O, O, O, O, B-VT, I-VT, I-VT, I-VT, I-VT, ..."
4,4,"[Der, Wortlaut, der, Zulagenregelung, verlange...","[14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 1...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O]"

In [19]:
fine_labels_merge = {
    'B-AN': 'Anwalt',
    'B-EUN': 'EU Norm',
    'B-GRT': 'Gericht',
    'B-GS': 'Gesetz',
    'B-INN': 'Institution',
    'B-LD': 'Land',
    'B-LDS': 'Landschaft',
    'B-LIT': 'Literatur',
    'B-MRK': 'Marke',
    'B-ORG': 'Organisation',
    'B-PER': 'Person',
    'B-RR': 'Richter',
    'B-RS': 'Gerichtsentscheidung',
    'B-ST': 'Stadt',
    'B-STR': 'Straße',
    'B-UN': 'Unternehmen',
    'B-VO': 'Verordnung',
    'B-VS': 'Vorschrift',
    'B-VT': 'Vertrag',
    'I-AN': 'Anwalt',
    'I-EUN': 'EU Norm',
    'I-GRT': 'Gericht',
    'I-GS': 'Gesetz',
    'I-INN': 'Institution',
    'I-LD': 'Land',
    'I-LDS': 'Landschaft',
    'I-LIT': 'Literatur',
    'I-MRK': 'Marke',
    'I-ORG': 'Organisation',   
    'I-PER': 'Person',
    'I-RR': 'Richter',
    'I-RS': 'Gerichtsentscheidung',
    'I-ST': 'Stadt',
    'I-STR': 'Straße',
    'I-UN': 'Unternehmen',
    'I-VO': 'Verordnung',
    'I-VS': 'Vorschrift',
    'I-VT': 'Vertrag',
    'O': 'O'
}

In [23]:
fine_labels_merge2id = {
    'O': 0,
    'Person': 1,
    'Anwalt': 2,
    'Richter': 3,
    'Land': 4,
    'Stadt': 5,
    'Straße': 6,
    'Landschaft': 7,
    'Organisation': 8,   
    'Unternehmen': 9,
    'Institution': 10,
    'Gericht': 11,
    'Marke': 12,
    'Gesetz': 13,
    'Verordnung': 14,
    'EU Norm': 15,
    'Vorschrift': 16,
    'Vertrag': 17,
    'Rechtsprechung': 18,
    'Literatur': 19,
}

In [42]:
fine_id2label = {i: label for i, label in enumerate(fine_labels_merge2id)}
fine_id2label

{0: 'O',
 1: 'Person',
 2: 'Anwalt',
 3: 'Richter',
 4: 'Land',
 5: 'Stadt',
 6: 'Straße',
 7: 'Landschaft',
 8: 'Organisation',
 9: 'Unternehmen',
 10: 'Institution',
 11: 'Gericht',
 12: 'Marke',
 13: 'Gesetz',
 14: 'Verordnung',
 15: 'EU Norm',
 16: 'Vorschrift',
 17: 'Vertrag',
 18: 'Gerichtsentscheidung',
 19: 'Literatur'}

In [20]:
df["fine_ner_tags"] = df["fine_ner_tags"].apply(lambda x: [fine_labels_merge[i] for i in x])

In [24]:
df["fine_ner_tags"] = df["fine_ner_tags"].apply(lambda x: [fine_labels_merge2id[i] for i in x])

In [25]:
df.head()

,id,tokens,ner_tags,fine_ner_tags
0,0,"[Wegen, der, Teilnahme, des, Antragstellers, a...","[14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 1...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, ..."
1,1,"[●, Mitwirkung, im, Sinne, der, Kostenverfügung]","[14, 14, 14, 14, 14, 14]","[0, 0, 0, 0, 0, 0]"
2,2,"[Von, der, Ablehnung, eines, Straferlasses, fü...","[14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 1...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,3,"[Zwar, führt, bei, der, in, §, 33, Abs., 2, TV...","[14, 14, 14, 14, 14, 5, 12, 12, 12, 12, 12, 12...","[0, 0, 0, 0, 0, 17, 17, 17, 17, 17, 17, 17, 0,..."
4,4,"[Der, Wortlaut, der, Zulagenregelung, verlange...","[14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 1...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"

In [35]:
coarse_labels = [
    'B-LIT', 
    'B-LOC', 
    'B-NRM', 
    'B-ORG', 
    'B-PER', 
    'B-REG', 
    'B-RS', 
    'I-LIT', 
    'I-LOC', 
    'I-NRM', 
    'I-ORG', 
    'I-PER', 
    'I-REG', 
    'I-RS', 
    'O'
]

In [28]:
id2coarse_label = {i: label for i, label in enumerate(coarse_labels)}

In [29]:
df["ner_tags"] = df["ner_tags"].apply(lambda x: [id2coarse_label[i] for i in x])

In [30]:
df.head()

,id,tokens,ner_tags,fine_ner_tags
0,0,"[Wegen, der, Teilnahme, des, Antragstellers, a...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, B-L...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, ..."
1,1,"[●, Mitwirkung, im, Sinne, der, Kostenverfügung]","[O, O, O, O, O, O]","[0, 0, 0, 0, 0, 0]"
2,2,"[Von, der, Ablehnung, eines, Straferlasses, fü...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,3,"[Zwar, führt, bei, der, in, §, 33, Abs., 2, TV...","[O, O, O, O, O, B-REG, I-REG, I-REG, I-REG, I-...","[0, 0, 0, 0, 0, 17, 17, 17, 17, 17, 17, 17, 0,..."
4,4,"[Der, Wortlaut, der, Zulagenregelung, verlange...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"

In [31]:
coarse_labels_merge = {
    'B-LIT': 'Literatur', 
    'B-LOC': 'Ort', 
    'B-NRM': 'Norm', 
    'B-ORG': 'Organisation', 
    'B-PER': 'Person', 
    'B-REG': 'Einzelfallregelung', 
    'B-RS': 'Rechtsprechung',  
    'I-LIT': 'Literatur', 
    'I-LOC': 'Ort', 
    'I-NRM': 'Norm', 
    'I-ORG': 'Organisation', 
    'I-PER': 'Person', 
    'I-REG': 'Einzelfallregelung', 
    'I-RS': 'Rechtsprechung', 
    'O': 'O'
}

In [32]:
coarse_labels_merge2id = {
    'O': 0,
    'Person': 1,
    'Ort': 2,
    'Organisation': 3,
    'Norm': 4,
    'Gesetz': 5,
    'Rechtsprechung': 6,
    'Literatur': 7,
}

In [40]:
coarse_id2label = {v: k for k, v in coarse_labels_merge2id.items()}
coarse_id2label

{0: 'O',
 1: 'Person',
 2: 'Ort',
 3: 'Organisation',
 4: 'Norm',
 5: 'Einzelfallregelung',
 6: 'Rechtsprechung',
 7: 'Literatur'}

In [ ]:
print("\n".join([(coarse_id2label.values()(lambda x: x.upper()))[1:]))

art
building
event
location
organization
other
person
product

In [33]:
df["ner_tags"] = df["ner_tags"].apply(lambda x: [coarse_labels_merge[i] for i in x])

In [34]:
df.head()

,id,tokens,ner_tags,fine_ner_tags
0,0,"[Wegen, der, Teilnahme, des, Antragstellers, a...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, Ort...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, ..."
1,1,"[●, Mitwirkung, im, Sinne, der, Kostenverfügung]","[O, O, O, O, O, O]","[0, 0, 0, 0, 0, 0]"
2,2,"[Von, der, Ablehnung, eines, Straferlasses, fü...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,3,"[Zwar, führt, bei, der, in, §, 33, Abs., 2, TV...","[O, O, O, O, O, Einzelfallregelung, Einzelfall...","[0, 0, 0, 0, 0, 17, 17, 17, 17, 17, 17, 17, 0,..."
4,4,"[Der, Wortlaut, der, Zulagenregelung, verlange...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"

In [36]:
df["ner_tags"] = df["ner_tags"].apply(lambda x: [coarse_labels_merge2id[i] for i in x])

In [37]:
df.head()

,id,tokens,ner_tags,fine_ner_tags
0,0,"[Wegen, der, Teilnahme, des, Antragstellers, a...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, ..."
1,1,"[●, Mitwirkung, im, Sinne, der, Kostenverfügung]","[0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0]"
2,2,"[Von, der, Ablehnung, eines, Straferlasses, fü...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,3,"[Zwar, führt, bei, der, in, §, 33, Abs., 2, TV...","[0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, ...","[0, 0, 0, 0, 0, 17, 17, 17, 17, 17, 17, 17, 0,..."
4,4,"[Der, Wortlaut, der, Zulagenregelung, verlange...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"

In [38]:
df.to_parquet("german_ler_test.parquet")